### ISSUE TITLE
Show current access token scopes

### ISSUE THREAD

**Issue by nbartels** [fbsamples/threads_api#10]
It would be great to see what scopes the user has approved, so we can get that information from the access token somehow. The manual access token debugger is nice, but in an enterprise environment you will not be able to manually check each access token in case of an error.

So, add some endpoints to the sample application and propagate the RFC to the API team. Maybe we can get a debug endpoint to check for a valid token.

**Comment by pestevez** [comment]
Thanks for the suggestion and the API request will be relayed to the appropriate team. Since the scope of this repository is to show what is supported in the Threads API, I will close this issue since it is not actionable for us.
