### ISSUE TITLE
Can't login and access the token 

### ISSUE THREAD

**Issue by heroaltman** [fbsamples/threads_api#14]
I am having an issue when I go to the OAuth URL with my client ID and redirect and scope here is the URL : https://www.threads.net/login?next=https://www.threads.net/oauth/authorize?client_id=2345xxxx&redirect_uri=https%3A%2F%2Fapp.abc.com%2Fauth%2Fthreads%2Fcallback&state=3a7441ea4&response_type=code&scope=threads_basic%2Cthreads_content_publish%2Cthreads_manage_insights%2Cthreads_manage_replies%2Cthreads_read_replies&__coig_login=1

but after logging in I get this error: {"error_message":"Invalid Request: The  user has not accepted the invite to test the app","error_code":1349245}

First of all, I don't know how to do this test user thing every time I try to create a test user I get this error : 
![image](https://github.com/fbsamples/threads_api/assets/132768203/a4d98db0-b467-4bb4-926e-6e8817c363b3)

Also, it's for test but I want to be able to do this without adding any test user I just want the user hit the OAuth URL approval and we get the access token and save it to use 

That's it but how to do it 

Please Help

**Comment by anujs3** [comment]
Hi @heroaltman! Have you looked at the Threads Tester section of the developer docs?

https://developers.facebook.com/docs/threads/get-started#threads-testers

It explains the process of adding a Threads tester and accepting the Tester invite on the Invites tab, which can be found after clicking on the "Website permissions" section under https://www.threads.net/settings/account.

**Comment by anujs3** [comment]
@heroaltman one more thing, after your app goes through the App Review process and is granted approval, then you should be able to publish your app and use Threads API without adding test users. 

https://developers.facebook.com/docs/development/create-an-app/threads-use-case#step-10--app-review

**Comment by anujs3** [comment]
@heroaltman I'm going to close this issue. Feel free to open a new issue if you're still stuck on this step. Thanks!
