### ISSUE TITLE
add threads-api and threads-app tag for better visibility

### ISSUE THREAD

**Issue by match-gabeflores** [fbsamples/threads_api#15]
for example, see tags on this other repo
[threads-api](https://github.com/topics/threads-api)

**Comment by anujs3** [comment]
Hi @match-gabeflores! When you say tags, do you mean topics? We can look into this.

**Comment by anujs3** [comment]
@match-gabeflores I added the `threads-api` and `threads-app` topics to https://github.com/fbsamples/threads_api:
<img width="317" alt="image" src="https://github.com/user-attachments/assets/c86af130-e56f-4213-8129-9bdf7c666c7c">

Thanks for suggesting this and helping us increase visibility of our sample app!
