### ISSUE TITLE
Unable to Login after following instructions in Readme

### ISSUE THREAD

**Issue by joeldenning** [fbsamples/threads_api#17]
I have set the APP_ID and API_SECRET environment variables in the `.env` file, but get the following error when trying to Login. Is there a specific setting in the Meta app that is required?

```json
{
error_message: "No application data was given: There was a problem getting data for an application. The application may not be valid or there is a temporary glitch. Please try again later.",
error_code: 1349026
}
```

**Comment by aLEGEND21** [comment]
I have the same issue. I have created an app with the Threads use case, set the redirect URL, and copied the App ID and App Secret from App settings > Basic. I also received the error message @joeldenning posted when manually trying to obtain a user access token from the following URL found in the documentation:
```
https://threads.net/oauth/authorize
  ?client_id=<THREADS_APP_ID>
  &redirect_uri=<REDIRECT_URI>
  &scope=<SCOPE>
  &response_type=code
  &state=<STATE> // Optional
```

**Comment by ziedak** [comment]
I have the same issue

{
error_message: "No application data was given: There was a problem getting data for an application. The application may not be valid or there is a temporary glitch. Please try again later.",
error_code: 1349026
}

**Comment by aLEGEND21** [comment]
I figured out the issue. I was using the App ID and App secret, not the **Threads** App ID and **Threads** App secret. You have to go to **App Dashboard > App settings > Basic** to find the Threads App ID and App secret. They're listed in a box below the regular App ID and App secret on that page.

**Comment by joeldenning** [comment]
Thanks @aLEGEND21 - changing to the Threads App ID and Threads App secret resolved this problem for me
