### ISSUE TITLE
Not able to set Redirect URL on dashboard

### ISSUE THREAD

**Issue by sjsj2100** [fbsamples/threads_api#18]
Hello! This might not be the problem of the repo, however, I'm not able to follow along with the README. Once I hit `Save` button, I get a form error popping up on the left bottom corner.

> 2. Make sure you add your application's redirect URL e.g. https://threads-sample.meta:8000/callback, to your app's redirect callback URLs in the app dashboard.

![Screenshot 2024-08-04 at 1 16 32 PM](https://github.com/user-attachments/assets/d3a585c6-86c5-4183-bb5f-ab7a1671b201)
<img width="348" alt="Screenshot 2024-08-04 at 1 19 48 PM" src="https://github.com/user-attachments/assets/766d6f6b-db06-4e52-acd7-3ed1a907a210">

As a result of not able to set the redirect URL, I get an error after logging in.
`{"error_message":"URL Blocked: This redirect failed because the redirect URI is not whitelisted in the app\u2019s Client OAuth Settings. Make sure Client and Web OAuth Login are on and add all your app domains as Valid OAuth Redirect URIs.","error_code":1349168}`

**Comment by anujs3** [comment]
Hi @sjsj2100! When you type in your redirect URL, you need to click on the dropdown popup button. Take a look at this screenshot below:
<img width="1212" alt="image" src="https://github.com/user-attachments/assets/d57821d8-33d1-422c-9447-7d3bf22d2a9e">

Once you do that, your redirect URL will be highlighted with a grey background. It should look something like this:
<img width="1178" alt="image" src="https://github.com/user-attachments/assets/084e05d1-20e7-476f-afaa-248ea2e39d70">

Try pressing the Save button after doing this. Let me know if that resolves your issue.

**Comment by sjsj2100** [comment]
@anujs3 Thank you so much! It's so strange that only the Redirect Callback URLs field is that way. 😄

**Comment by sjsj2100** [comment]
As @anujs3 suggestion, for the Redirect Callback URLs fields it's required to be selected from the popup dropdown. Although this is work around, I think it's still a bug in the console UI. (or at least there's a lack of indication)
