### ISSUE TITLE
No way to report a bug

### ISSUE THREAD

**Issue by pgib** [fbsamples/threads_api#25]
It's very frustrating to not be able to report a bug regarding the Threads API, so reporting things here.

![image](https://github.com/user-attachments/assets/8e55dc4a-91be-4ba3-aa30-bf42396cc2b5)

**Comment by pgib** [comment]
@nickfryar Hey Nick – we're having a really hard time reporting bugs to anyone on the Threads team because Meta doesn't accept bug reports, no one (at Meta) responds in the developer community, and [Adam Mosseri](https://www.threads.net/@mosseri) is probably not seeing things given how many people are likely mentioning him. Are you able to help here? I've created some issues in this repo.

**Comment by pestevez** [comment]
Hey @pgib - I understand this is an inconvenience but unfortunately the Developer Community is the only available channel now. I'll take a look at the issues that you have reported, but I will close the issues as they are not related to the sample app itself.

**Comment by pgib** [comment]
> Hey @pgib - I understand this is an inconvenience but unfortunately the Developer Community is the only available channel now. I'll take a look at the issues that you have reported, but I will close the issues as they are not related to the sample app itself.

@pestevez Thank you. The Developer Community is not a viable channel because no one from Meta seems to look at it. Why don't you accept bug reports through your actual bug report channel?
