### ISSUE TITLE
Carousel posts with video content fail

### ISSUE THREAD

**Issue by pgib** [fbsamples/threads_api#26]
Details posted here, but creating a carousel post with a video container always fail. Single item posts with video sometimes fail in a similar manner, too.

https://developers.facebook.com/community/threads/498350122863751/

**Comment by pgib** [comment]
A further clue that I discovered is that the problem happens when the unpublished carousel thread (where there is at least one video item) is created and then immediately published. Putting some time between the two requests seems to resolve it; however, there is no documentation around this nor is there any way clear to query for readiness in between.

**Comment by pestevez** [comment]
Yeah, I saw your comment in the Community portal. We will update the documentation to make it clearer that it is recommended to wait for the `FINISHED` status of the container.
This what we do in the sample app ([server side](https://github.com/fbsamples/threads_api/blob/main/src/index.js#L407), [client side](https://github.com/fbsamples/threads_api/main/public/scripts/publish.js#L41C15-L41C23)).

**Comment by pestevez** [comment]
Yeah, I saw your comment in the Community portal. We will update the documentation to make it clearer that it is recommended to wait for the `FINISHED` status of the container.
This what we do in the sample app ([server side](https://github.com/fbsamples/threads_api/blob/main/src/index.js#L407), [client side](https://github.com/fbsamples/threads_api/blob/564b542c237b033b52744703fda4b82427db2f4f/public/scripts/publish.js#L41C15-L41C23)).
