### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by paulorsr** [fbsamples/threads_api#4]
Hello, after running the app and allowing requesting access I just see this message:

![Screenshot from 2024-06-18 17-38-49](https://github.com/fbsamples/threads_api/assets/6306794/1d07b7bd-5e31-4130-84cd-f1d63820f283)

**Comment by kareem1234** [comment]
Are you able to provide reproduction instructions ?

**Comment by paulorsr** [comment]
Without any change it seems to work fine today. Thanks anyway!
