### ISSUE TITLE
Cannot accept Invitation my account

### ISSUE THREAD

**Issue by tinhnguyeninfo1988** [fbsamples/threads_api#8]
hi team, i'm trying to login with my account (same account who created the app) but there are no any notification/link to accept the Invitation, please help
![image](https://github.com/fbsamples/threads_api/assets/80885722/8070a660-1564-43c7-ade7-ad6981fa311f)
![image](https://github.com/fbsamples/threads_api/assets/80885722/2e4eed13-4a8d-4c49-9796-79e555a9b21a)

**Comment by tinhnguyeninfo1988** [comment]
finally found the link to accept but still can not login, please help
![image](https://github.com/fbsamples/threads_api/assets/80885722/954d97f7-fed7-4700-a23b-5a4632175d28)

**Comment by pestevez** [comment]
Thanks for reaching out. Are you still experiencing this issue? If so, my recommendation is that you file a [Platform bug report](https://developers.facebook.com/support/bugs/).

Since the scope of this repository is to show how the Threads API works, I am closing this issue since it is not actionable for us.

**Comment by anujs3** [comment]
@tinhnguyeninfo1988 I hope that you were able to find the section where you can accept the tester invite; in the developer docs, it mentions that the Invites tab can be found by clicking on the "Website permissions" section under https://www.threads.net/settings/account:

https://developers.facebook.com/docs/threads/get-started#threads-testers

Let us know if these docs helped resolve your issue.

**Comment by tinhnguyeninfo1988** [comment]
thanks @anujs3 , everything working well now
